In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,roc_curve,classification_report
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV

import warnings
warnings.filterwarnings('ignore')

In [4]:
df=pd.read_csv('E_Commerce_data.csv')
df

,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,50001,1,4.0,Mobile Phone,3,6.0,Debit Card,Female,3.0,3,Laptop & Accessory,2,Single,9,1,11.0,1.0,1.0,5.0,159.93
1,50002,1,NaN,Phone,1,8.0,UPI,Male,3.0,4,Mobile,3,Single,7,1,15.0,0.0,1.0,0.0,120.90
2,50003,1,NaN,Phone,1,30.0,Debit Card,Male,2.0,4,Mobile,3,Single,6,1,14.0,0.0,1.0,3.0,120.28
3,50004,1,0.0,Phone,3,15.0,Debit Card,Male,2.0,4,Laptop & Accessory,5,Single,8,0,23.0,0.0,1.0,3.0,134.07
4,50005,1,0.0,Phone,1,12.0,CC,Male,NaN,3,Mobile,5,Single,3,0,11.0,1.0,1.0,3.0,129.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,99996,0,1.0,Mobile Phone,1,6.0,COD,Male,2.0,4,Laptop & Accessory,4,Married,5,0,12.0,1.0,8.0,13.0,190.02
49996,99997,0,10.0,Mobile Phone,1,10.0,Credit Card,Male,3.0,4,Fashion,1,Single,10,0,13.0,0.0,2.0,7.0,229.47
49997,99998,0,11.0,Phone,1,16.0,Debit Card,Male,3.0,3,Audio Devices,5,Divorced,2,0,14.0,1.0,1.0,9.0,320.13
49998,99999,0,28.0,Phone,3,12.0,Debit Card,Male,2.0,2,Laptop & Accessory,3,Single,3,0,13.0,2.0,4.0,8.0,150.98
49999,100000,0,17.0,Phone,1,35.0,E wallet,Female,3.0,2,Laptop & Accessory,4,Single,2,1,18.0,6.0,4.0,3.0,187.93

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   CustomerID                   50000 non-null  int64
 1   Churn                        50000 non-null  int64
 2   Tenure                       49736 non-null  float64
 3   PreferredLoginDevice         50000 non-null  object
 4   CityTier                     50000 non-null  int64
 5   WarehouseToHome              49749 non-null  float64
 6   PreferredPaymentMode         50000 non-null  object
 7   Gender                       50000 non-null  object
 8   HourSpendOnApp               49745 non-null  float64
 9   NumberOfDeviceRegistered     50000 non-null  int64
 10  PreferedOrderCat             50000 non-null  object
 11  SatisfactionScore            50000 non-null  int64
 12  MaritalStatus                50000 non-null  object
 13  NumberOfAddress              50000 non-null  int64
 14  Complain                     50000 non-null  int64
 15  OrderAmountHikeFromlastYear  49735 non-null  float64
 16  CouponUsed                   49744 non-null  float64
 17  OrderCount                   49742 non-null  float64
 18  DaySinceLastOrder            49693 non-null  float64
 19  CashbackAmount               50000 non-null  float64
dtypes: float64(8), int64(7), object(5)
memory usage: 7.6+ MB

In [6]:
df.describe()

,CustomerID,Churn,Tenure,CityTier,WarehouseToHome,HourSpendOnApp,NumberOfDeviceRegistered,SatisfactionScore,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
count,50000.000000,50000.000000,49736.000000,50000.000000,49749.000000,49745.000000,50000.000000,50000.000000,50000.000000,50000.000000,49735.000000,49744.000000,49742.000000,49693.000000,50000.000000
mean,75000.500000,0.170100,10.137385,1.644900,15.646465,2.929460,3.701300,3.060680,4.225160,0.283180,15.709420,1.734259,3.014736,4.532892,177.382610
std,14433.901067,0.375724,8.525396,0.911559,8.485831,0.718297,1.019754,1.376734,2.595534,0.450548,3.673604,1.876246,2.952878,3.626286,49.304958
min,50001.000000,0.000000,0.000000,1.000000,5.000000,0.000000,1.000000,1.000000,1.000000,0.000000,11.000000,0.000000,1.000000,0.000000,0.000000
25%,62500.750000,0.000000,2.000000,1.000000,9.000000,2.000000,3.000000,2.000000,2.000000,0.000000,13.000000,1.000000,1.000000,2.000000,145.860000
50%,75000.500000,0.000000,9.000000,1.000000,14.000000,3.000000,4.000000,3.000000,3.000000,0.000000,15.000000,1.000000,2.000000,3.000000,163.150000
75%,87500.250000,0.000000,16.000000,3.000000,21.000000,3.000000,4.000000,4.000000,6.000000,1.000000,18.000000,2.000000,3.000000,7.000000,196.790000
max,100000.000000,1.000000,61.000000,3.000000,127.000000,5.000000,6.000000,5.000000,22.000000,1.000000,26.000000,16.000000,16.000000,46.000000,324.990000